# Generated by Django 4.2.3 on 2023-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_file_file_type_alter_file_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'PDF')], verbose_name='File Type'),
        ),
    ]
